"""empty message

Revision ID: 06bdcf24108b
Revises: ea6801ca2f5e
Create Date: 2025-04-22 15:00:27.781394

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06bdcf24108b'
down_revision = 'ea6801ca2f5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mcp_tool', schema=None) as batch_op:
        batch_op.drop_column('host')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mcp_tool', schema=None) as batch_op:
        batch_op.add_column(sa.Column('host', sa.VARCHAR(length=255), server_default=sa.text("''::character varying"), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
