"""empty message

Revision ID: 3f3cc214dfd6
Revises: 5e09519ceecb
Create Date: 2025-02-20 15:39:22.781314

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f3cc214dfd6'
down_revision = '5e09519ceecb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app', schema=None) as batch_op:
        batch_op.add_column(sa.Column('token', sa.String(length=255), server_default=sa.text("''::character varying"), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app', schema=None) as batch_op:
        batch_op.drop_column('token')

    # ### end Alembic commands ###
