"""empty message

Revision ID: 774011890ba6
Revises: aa6c9ab3fa8b
Create Date: 2025-05-10 10:41:34.415764

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '774011890ba6'
down_revision = 'aa6c9ab3fa8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app_config_version', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mcps', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app_config_version', schema=None) as batch_op:
        batch_op.drop_column('mcps')

    # ### end Alembic commands ###
