"""empty message

Revision ID: 89f41952bc56
Revises: 20d24493e7e7
Create Date: 2025-04-08 20:45:24.410894

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '89f41952bc56'
down_revision = '20d24493e7e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mcp_tool',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), server_default=sa.text("''::character varying"), nullable=False),
    sa.Column('host', sa.String(length=255), server_default=sa.text("''::character varying"), nullable=False),
    sa.Column('icon', sa.String(length=255), server_default=sa.text("''::character varying"), nullable=False),
    sa.Column('description', sa.Text(), server_default=sa.text("''::text"), nullable=False),
    sa.Column('api_key', sa.String(length=255), server_default=sa.text("''::character varying"), nullable=False),
    sa.Column('transport_type', sa.String(length=255), server_default=sa.text("''::character varying"), nullable=False),
    sa.Column('parameters', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP(0)'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP(0)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name='pk_mcp_tool_id')
    )
    with op.batch_alter_table('mcp_tool', schema=None) as batch_op:
        batch_op.create_index('mcp_tool_account_id_idx', ['account_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mcp_tool', schema=None) as batch_op:
        batch_op.drop_index('mcp_tool_account_id_idx')

    op.drop_table('mcp_tool')
    # ### end Alembic commands ###
