"""empty message

Revision ID: ea6801ca2f5e
Revises: 89f41952bc56
Create Date: 2025-04-13 10:22:22.995470

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea6801ca2f5e'
down_revision = '89f41952bc56'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ex_link_token', sa.String(length=255), server_default=sa.text("''::character varying"), nullable=True))

    with op.batch_alter_table('mcp_tool', schema=None) as batch_op:
        batch_op.add_column(sa.Column('provider_name', sa.String(length=255), server_default=sa.text("''::character varying"), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mcp_tool', schema=None) as batch_op:
        batch_op.drop_column('provider_name')

    with op.batch_alter_table('app', schema=None) as batch_op:
        batch_op.drop_column('ex_link_token')

    # ### end Alembic commands ###
